name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Không dùng cache tích hợp ở đây

    # Tạo cache thủ công
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: frontend/think-space/node_modules  # Cache thư mục node_modules trong đúng thư mục
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-frontend-think-space
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-

    # Cài dependencies từ đúng thư mục
    - name: Install dependencies
      run: npm ci
      working-directory: frontend/think-space  # Đặt đúng thư mục làm việc

    # Build ứng dụng từ đúng thư mục
    - name: Build application
      run: npm run build --if-present
      working-directory: frontend/think-space

    # Chạy tests từ đúng thư mục
    - name: Run tests
      run: npm test
      working-directory: frontend/think-space
